### ISSUE TITLE
Image Panel not auto refreshing.

### ISSUE THREAD

**Issue by Alex-Pennington** [mycontroller-org/server#27]
The image is only refreshed when the browser refresh button is clicked.  Tested from MS Edge and Chrome.

Panel YAML:
```
id: e1b392ad-fec2-4ceb-8534-8ffa48d9a5f5
title: Panel Title
showTitle: false
scrollbarDisabled: true
static: false
type: widget_image_panel
layout:
  w: 23
  h: 69
  x: 52
  'y': 158
config:
  field: {}
  imageURL: http://192.168.1.210/tmpfs/auto.jpg
  refreshInterval: 60000
  rotation: '0'
  sourceType: url
```
