### ISSUE TITLE
Utilization Table View Displays NaN for V_TEXT

### ISSUE THREAD

**Issue by Alex-Pennington** [mycontroller-org/server#28]
I have a node that reports error and other status data via V_TEXT.  When I look at the field details I can see that mycontroller has received the string data correctly.  But it displays NaN in the Utilization Table View.  Not sure if this is a bug or intended behavior.

Widget YAML

```id: 5592fa60-e17e-4338-b6fb-696aafcd0327
title: Info
showTitle: true
scrollbarDisabled: false
static: false
type: widget_utilization_panel
layout:
  w: 47
  h: 35
  x: 1
  'y': 0
config:
  hideBorder: true
  resource:
    displayName: true
    filter:
      labels.ms_sensor_id: '68'
      nodeId: '201'
    filterType: detailed_filter
    isMixedResources: false
    limit: 1
    nameKey: Info
    quickId: ''
    resources: []
    roundDecimal: 0
    timestampKey: current.timestamp
    type: field
    unit: ''
    valueKey: current.value
  table:
    displayStatusPercentage: true
    hideBorder: false
    hideStatusColumn: true
    hideValueColumn: false
    maximumValue: 100
    minimumValue: 0
    thresholds: {}
  type: table

**Comment by jkandasa** [comment]
hi @Alex-Pennington I am unable to reproduce this issue
Can you please share the followings?
* Field `V_TEXT` data in yaml format
* do you see an error on browser console?
* screenshot of the error on browser

I tried the following settings and it works,

#### Widget:
```yaml
id: ed2a40c6-dc68-4d6c-b505-d15e811bf56c
title: Info
showTitle: true
scrollbarDisabled: false
static: false
type: widget_utilization_panel
layout:
  w: 47
  h: 120
  x: 0
  'y': 158
config:
  hideBorder: true
  resource:
    displayName: true
    filter:
      gatewayId: mysensor
      nodeId: '32'
    filterType: detailed_filter
    isMixedResources: false
    limit: 10
    nameKey: fieldId
    quickId: ''
    resources: []
    roundDecimal: 0
    timestampKey: current.timestamp
    type: field
    unit: ''
    valueKey: current.value
  table:
    displayStatusPercentage: true
    hideBorder: false
    hideStatusColumn: true
    hideValueColumn: false
    maximumValue: 100
    minimumValue: 0
    thresholds: {}
  type: table
```
#### Field data:
```yaml
id: 4d261fe1-34a2-4c5a-a0ca-4fd1a608942c
gatewayId: mysensor
nodeId: '32'
sourceId: '1'
fieldId: V_TEXT
name: V_TEXT
metricType: none
current:
  value: E:date not received
  isReceived: true
  timestamp: '2025-02-16T00:45:25.96822797+05:30'
previous:
  value: E:date not received
  isReceived: true
  timestamp: '2025-02-15T20:30:58.641843652+05:30'
formatter:
  onReceive: ''
unit: ''
labels:
  ms_node_id: '32'
  ms_sensor_id: '1'
  ms_type: '47'
  ms_type_string: V_TEXT
others: {}
noChangeSince: '2025-02-13T14:16:27.135611772+05:30'
lastSeen: '2025-02-16T00:45:25.96822797+05:30'
modifiedOn: '0001-01-01T00:00:00Z'

```

![Image](https://github.com/user-attachments/assets/5baf470b-da0e-4e86-a64b-6e1c6bb1f9eb)
